org.gradle.jvmargs=-Xmx512m -XX:MaxMetaspaceSize=256m -XX:ReservedCodeCacheSize=32m -Xss256k -XX:+UseSerialGC -XX:TieredStopAtLevel=1
kotlin.daemon.jvm.options=-Xmx256m -XX:MaxMetaspaceSize=256m -XX:TieredStopAtLevel=1
org.gradle.daemon=false
org.gradle.workers.max=1
org.gradle.parallel=false
org.gradle.configureondemand=true
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false
